from rdflib import URIRef

namespaces = {'station_namespace':URIRef('http://tfl.gov.uk/tfl#Station'),
		'station_id':URIRef('http://tfl.gov.uk/tfl#Stationid'),
		'station_type':URIRef('http://tfl.gov.uk/tfl#Stationtype'),
		'station_name':URIRef('http://tfl.gov.uk/tfl#StationName'),
		'serviceline':URIRef('http://tfl.gov.uk/tfl#serviceline'),
		'servicezone':URIRef('http://tfl.gov.uk/tfl#zone'),
		'contactdetails': URIRef('http://tfl.gov.uk/tfl#contactdetails'),
		'contactdetailsaddress': URIRef('http://tfl.gov.uk/tfl#contactdetailsaddress'),
		'contactdetailsphone': URIRef('http://tfl.gov.uk/tfl#contactdetailsphone'),
		'facilities': URIRef('http://tfl.gov.uk/tlf#facilities'),
		'naptans': URIRef('http://tfl.gov.uk/tlf#naptans'),
		'lines': URIRef('http://tfl.gov.uk/tfl#lines'),
		'entrance': URIRef('http://tfl.gov.uk/tfl#entrance'),
		'entrances': URIRef('http://tfl.gov.uk/tfl#entrances'),
		'entrancename' : URIRef('http://tfl.gov.uk/tfl#entrancename'),
		'entrancetobookhall': URIRef('http://tfl.gov.uk/tfl#entranceToBookingHall'),
		'entrancebookingplatform': URIRef('http://tfl.gov.uk/tfl#BookintHallToPlatform'),
		'path': URIRef('http://tfl.gov.uk/tfl#path'),
		'heading':URIRef('http://tfl.gov.uk/tfl#heading'),
		'pathdescription': URIRef('http://tfl.gov.uk/tfl#pathDescription'),
		'plathformtotrain': URIRef('http://tfl.gov.uk/tfl#pathformToTrain'),
		'trainname': URIRef('http://tfl.gov.uk/tfl#trainName'),
		'platformtotrainsteps': URIRef('http://tfl.gov.uk/tfl#plathformToTrainSteps'),
		'pointname':URIRef('http://tfl.gov.uk/tfl#pointName'),
		'placemark': URIRef('http://tfl.gov.uk/tfl#Placemark'),
		'placemarkname': URIRef('http://tfl.gov.uk/tfl#Placemarkname'),
		'placemarkdescription':URIRef('http://tfl.gov.uk/tfl#PlacemarkDescription'),
		'placemarkpoint': URIRef('http://tfl.gov.uk/tfl#PlacemarkPoint'),
		'placemarkcoordinates': URIRef('http://tfl.gov.uk/tfl#PlacemarkCoordinates'),
		'styleurl': URIRef('http://tfl.gov.uk/tfl#styleUrl'),
		'location': URIRef('http://tfl.gov.uk/tfl#Location'),
		'paymentrequired': URIRef('http://tfl.gov.uk/tfl#PaymentRequired'),
		'accessibility': URIRef('http://tfl.gov.uk/tfl#Accessibility'),
		'additionalaccessibilityinformation': URIRef('http://tfl.gov.uk/tfl#AdditionalAccessibilityInformation'),
		'bluebadgecarparkspaces': URIRef('http://tfl.gov.uk/tfl#BlueBadgeCarParkSpaces'),
		'taxiranksoutsidestation': URIRef('http://tfl.gov.uk/tfl#TaxiRanksOutsideStation'),
		'lift': URIRef('http://tfl.gov.uk/tfl#Lift'),
		'hasAccessVialift': URIRef('http://tfl.gov.uk/tfl#AccessViaLift'),
		'hasLimitedCapacityLift': URIRef('http://tfl.gov.uk/tfl#LimitedCapacityLift'),
		'Toilets':URIRef('http://tfl.gov.uk/tfl#Toilets'),
		'ToiletsLocation':URIRef('http://tfl.gov.uk/tfl#ToiletsLocation'),
		'Toiletspaymentrequired':URIRef('http://tfl.gov.uk/tfl#Toiletspaymentrequired'),
		'accessibletoilet': URIRef('http://tfl.gov.uk/tfl#AccessibleToilet'),
		'hasSpecificEntrance': URIRef('http://tfl.gov.uk/tfl#SpecificEntrance'),
		'specificEntranceRequired': URIRef('http://tfl.gov.uk/tfl#SpecificEntranceRequired'),
		'specificEntranceInstructions':URIRef('http://tfl.gov.uk/tfl#SpecificEntranceInstructions'),
		'accessibilityType': URIRef('http://tfl.gov.uk/tfl#AccessibilityType'),
		'airportInterchange': URIRef('http://tfl.gov.uk/tfl#AirportInterchange'),
		'pierInterchange': URIRef('http://tfl.gov.uk/tfl#PierInterchange'),
		'mainBusInterchange':URIRef('http://tfl.gov.uk/tfl#MainBusInterchange'),
		'emiratesAirLineInterchange': URIRef('http://tfl.gov.uk/tfl#EmiratesAirLineInterchange'),
		'tramlinkInterchange': URIRef('http://tfl.gov.uk/tfl#TramlinkInterchange'),
		'nationalRailInterchange': URIRef('http://tfl.gov.uk/tfl#NationalRailInterchange'),
		'accessibleInterchanges': URIRef('http://tfl.gov.uk/tfl#AccessibleInterchanges'),
		'lineName': URIRef('http://tfl.gov.uk/tfl#LineName'),
		'platform': URIRef('http://tfl.gov.uk/tfl#Platform'),
		'directionTowards': URIRef('http://tfl.gov.uk/tfl#DirectionTowards'),
		'stepMin': URIRef('http://tfl.gov.uk/tfl#StepMin'),
		'stepMax': URIRef('http://tfl.gov.uk/tfl#StepMax'),
		'gapMin': URIRef('http://tfl.gov.uk/tfl#GapMin'),
		'gapMax': URIRef('http://tfl.gov.uk/tfl#GapMax'),
		'levelAccessByManualRamp': URIRef('http://tfl.gov.uk/tfl#LevelAccessByManualRamp'),
		'locationOfLevelAccess': URIRef('http://tfl.gov.uk/tfl#LocationOfLevelAccess'),
		'naptan': URIRef('http://tfl.gov.uk/tfl#naptan'),
		'description': URIRef('http://tfl.gov.uk/tfl#Description'),
		'naptanId': URIRef('http://tfl.gov.uk/tfl#NaptanID'),
		'Ticket Halls':URIRef('http://tfl.gov.uk/tfl#TicketHalls'),
		'Lifts':URIRef('http://tfl.gov.uk/tfl#Lifts'),
		'Escalators': URIRef('http://tfl.gov.uk/tfl#Escalators'),
		'Gates': URIRef('http://tfl.gov.uk/tfl#Gates'),
		'Photo Booths': URIRef('http://tfl.gov.uk/tfl#PhotoBooths'),
		'Cash Machines': URIRef('http://tfl.gov.uk/tfl#CashMachines'),
		'Payphones': URIRef('http://tfl.gov.uk/tfl#Payphones'),
		'Car park': URIRef('http://tfl.gov.uk/tfl#CarPark'),
		'Vending Machines': URIRef('http://tfl.gov.uk/tfl#VendingMachines'),
		'Help Points': URIRef('http://tfl.gov.uk/tfl#HelpPoints'),
		'Bridge': URIRef('http://tfl.gov.uk/tfl#Bridge'),
		'Waiting Room': URIRef('http://tfl.gov.uk/tfl#WaitingRoom'),
		'Other Facilities': URIRef('http://tfl.gov.uk/tfl#OtherFacilities'),
		'zones': URIRef('http://tfl.gov.uk/tfl#Zones'),
		'zone': URIRef('http://tfl.gov.uk/tfl#Zone'),
		'direction': URIRef('http://tfl.gov.uk/tfl#Direction')}